language: r
cache: packages
sudo: false
fast_finish: true
install:
  - Rscript -e 'install.packages(c("readxl", "rjson", "stringr", "org.Hs.eg.db", "xlsx", "tm", "slam"))'
script:
  - cd code
  - Rscript ./AACR2018.R
