language: r
cache: packages
sudo: true
fast_finish: true
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - sudo ./setup_aws_cli.sh || travis_terminate 1
  - Rscript -e 'install.packages(c("readxl", "readr","dplyr", "rjson", "stringr", "xlsx", "tm", "slam"))'
stages:
  - name: build
    if: type = pull_request
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: build
      script:
        - cd code
        - Rscript ./config_smi.R
        - Rscript ./create_interactome_files.R
        - Rscript ./config_adc.R
        - Rscript ./create_interactome_files.R
    - stage: deploy
      script:
        - cd code
        - Rscript ./config_smi.R
        - Rscript ./create_interactome_files.R
        - Rscript ./config_adc.R
        - Rscript ./create_interactome_files.R
        - sudo aws s3 sync --acl public-read ../interactome/ s3://cancer.sagebionetworks.org
